exports.PARAM_REQUIRED = "PARAM REQUIRED";
exports.PRODUCT_NOT_ENABLE = "PRODUCT NOT ENABLE";
exports.INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";
exports.INVALID_COUPON = "INVALID COUPON";
exports.CUPON_NOT_APPLIED = "CUPON NOT APPLIED";
exports.PAYMENT_NOT_PROCESSED = "PAYMENT NOT PROCESSED";
exports.BILLING_CAN_NOT_BE_GENERATED = "BILLING CAN NOT BE GENERATED";

